name: Sync to Hugging Face hub

on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
          
      - name: Install Git LFS and huggingface-cli
        run: |
          sudo apt-get update
          sudo apt-get install python3-pip
          python -m venv .env
          source .env/bin/activate
          pip3 install --upgrade huggingface_hub
          huggingface-cli lfs-enable-largefiles ${{ github.workspace }}
          git lfs install
          git lfs track "*.jpg"
          
          
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push --force https://maksymalist:$HF_TOKEN@huggingface.co/maksymalist/junk-judge main
        
